[2024-02-07T17:01:22.427+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver-search-pipeline.chk_api_data manual__2024-02-07T08:01:17.757100+00:00 [queued]>
[2024-02-07T17:01:22.431+0900] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver-search-pipeline.chk_api_data manual__2024-02-07T08:01:17.757100+00:00 [queued]>
[2024-02-07T17:01:22.431+0900] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-07T17:01:22.440+0900] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): chk_api_data> on 2024-02-07 08:01:17.757100+00:00
[2024-02-07T17:01:22.442+0900] {standard_task_runner.py:57} INFO - Started process 178131 to run task
[2024-02-07T17:01:22.443+0900] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'naver-search-pipeline', 'chk_api_data', 'manual__2024-02-07T08:01:17.757100+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/naver_search_pipeline.py', '--cfg-path', '/tmp/tmpfwymqvc9']
[2024-02-07T17:01:22.444+0900] {standard_task_runner.py:85} INFO - Job 61: Subtask chk_api_data
[2024-02-07T17:01:22.461+0900] {task_command.py:410} INFO - Running <TaskInstance: naver-search-pipeline.chk_api_data manual__2024-02-07T08:01:17.757100+00:00 [running]> on host localhost
[2024-02-07T17:01:22.495+0900] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='naver-search-pipeline' AIRFLOW_CTX_TASK_ID='chk_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T08:01:17.757100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-07T08:01:17.757100+00:00'
[2024-02-07T17:01:22.498+0900] {logging_mixin.py:150} INFO - Event created: {'message': '이상 이벤트 : 데이터의 길이가 10 이하입니다.', 'data_length': 0}
[2024-02-07T17:01:22.498+0900] {python.py:183} INFO - Done. Returned value was: None
[2024-02-07T17:01:22.501+0900] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=naver-search-pipeline, task_id=chk_api_data, execution_date=20240207T080117, start_date=20240207T080122, end_date=20240207T080122
[2024-02-07T17:01:22.535+0900] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-07T17:01:22.546+0900] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
